name: Lab 4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "lab4" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lab3

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: make
      run: make
